name = "Echoing Hearths"
author = "OhItsElectric"
version = "0.2.7.1"
description = "Echoing HearthsSMP, a modpack for group of Friends of the Tavern"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af408dce976e46f073fb96c08af74baaa55ed5d6feff987ce41812879f86fad7"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
