name = "Echoing Hearths"
author = "OhItsElectric"
version = "0.0.15"
description = "Echoing HearthsSMP, a modpack for group of Friends of the Tavern"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca2cf7e580c13b2740384c8b25062b7eb7bb260cd10e0e749b57a6e5230815df"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
