name = "Echoing Hearths"
author = "OhItsElectric"
version = "0.2.5"
description = "Echoing HearthsSMP, a modpack for group of Friends of the Tavern"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a63419b407b109014bcbd1875849522100d5fad97ecdadcab3c93ba3cbe8f84"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
